source "https://rubygems.org"
gem "rails", "~> 7.2.0.beta3"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false
gem "httparty"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "faker"
  gem "dotenv-rails"
  gem "pry", "~> 0.14"
  gem "pry-byebug", "~> 3.10"
  gem "pry-rails"
end

group :test do
  gem "simplecov", "~> 0.21", require: false
  gem "simplecov_json_formatter"
  gem "vcr", "~> 6.2"
  gem "webmock"
  gem "database_cleaner-active_record"
end
