"afeganistao": 🇦🇫
"africa do sul": 🇿🇦
"albania": 🇦🇱
"andorra": 🇦🇩
"angola": 🇦🇴
"antigua e barbuda": 🇦🇬
"arabia saudita": 🇸🇦
"argelia": 🇩🇿
"armenia": 🇦🇲
"aruba": 🇦🇼
"australia": 🇦🇺
"austria": 🇦🇹
"azerbaijao": 🇦🇿
"bahamas": 🇧🇸
"bahrein": 🇧🇭
"bangladesh": 🇧🇩
"barbados": 🇧🇧
"belize": 🇧🇿
"benin": 🇧🇯
"bermudas": 🇧🇲
"bolivia": 🇧🇴
"bosnia e herzegovina": 🇧🇦
"botswana": 🇧🇼
"brunei darussalam": 🇧🇳
"bulgaria": 🇧🇬
"burkina faso": 🇧🇫
"burundi": 🇧🇮
"butao": 🇧🇹
"cabo verde": 🇨🇻
"camarões": 🇨🇲
"camboja": 🇰🇭
"catar": 🇶🇦
"chade": 🇹🇩
"chile": 🇨🇱
"chipre": 🇨🇾
"china": 🇨🇳
"colombia": 🇨🇴
"comores": 🇰🇲
"congo": 🇨🇬
"costa rica": 🇨🇷
"cote d'ivoire": 🇨🇮
"cuba": 🇨🇺
"djibuti": 🇩🇯
"dominica": 🇩🇲
"el salvador": 🇸🇻
"emirados arabes unidos": 🇦🇪
"eritrea": 🇪🇷
"estonia": 🇪🇪
"espanha": 🇪🇸
"eua": 🇺🇸
"finlandia": 🇫🇮
"franca": 🇫🇷
"gabao": 🇬🇦
"gambia": 🇲🇱
"ghana": 🇬🇭
"guam": 🇲🇵
"guiana": 🇬🇾
"guine": 🇲🇱
"guine equatorial": 🇨🇴
"guine-bissau": 🇬🇼
"honduras": 🇭🇳
"haiti": 🇭🇹
"hong kong, china": 🇭🇰
"hungria": 🇭🇺
"indonesia": 🇲🇨
"india": 🇮🇳
"iraque": 🇮🇶
"irlanda": 🇮🇪
"islandia": 🇮🇸
"israel": 🇮🇱
"italia": 🇮🇹
"jamaica": 🇯🇲
"japao": 🇯🇵
"jordania": 🇯🇴
"quenia": 🇰🇪
"kiribati": 🇰🇮
"kuwait": 🇰🇼
"laos": 🇱🇦
"letonia": 🇱🇻
"libano": 🇱🇧
"liberia": 🇱🇸
"libia": 🇱🇾
"liechtenstein": 🇱🇮
"luxemburgo": 🇱🇺
"madagascar": 🇲🇬
"malasia": 🇲🇾
"malawi": 🇲🇼
"maldivas": 🇲🇻
"mali": 🇲🇱
"malta": 🇲🇹
"marrocos": 🇲🇦
"mauritania": 🇲🇷
"micronesia": 🇫🇲
"monaco": 🇲🇨
"montenegro": 🇲🇪
"moçambique": 🇲🇿
"mianmar": 🇲🇲
"namibia": 🇳🇦
"nauru": 🇳🇷
"nepal": 🇳🇵
"nicaragua": 🇳🇮
"niger": 🇳🇪
"nigeria": 🇳🇬
"omã": 🇴🇲
"palau": 🇵🇼
"panama": 🇵🇦
"papua nova guine": 🇵🇬
"paquistao": 🇵🇰
"paraguai": 🇵🇾
"peru": 🇵🇪
"porto rico": 🇵🇷
"rep. centroafricana": 🇨🇫
"rep. arabe siria": 🇸🇾
"rep. islâmica ira": 🇮🇷
"ruanda": 🇷🇼
"santa lucia": 🇱🇨
"san marino": 🇸🇲
"sao tome e principe": 🇸🇹
"senegal": 🇸🇳
"seicheles": 🇸🇨
"serra leoa": 🇸🇱
"singapura": 🇸🇬
"somalia": 🇸🇴
"sri lanka": 🇱🇰
"sudan do sul": 🇸🇸
"sudan": 🇸🇩
"suriname": 🇸🇷
"essuatini": 🇸🇿
"tailandia": 🇹🇭
"tanzania": 🇹🇿
"timor leste": 🇹🇱
"togo": 🇹🇬
"tonga": 🇹🇴
"trinidad e tobago": 🇹🇹
"turcomenistao": 🇹🇲
"tuvalu": 🇹🇻
"uruguai": 🇺🇾
"vanuatu": 🇻🇺
"venezuela": 🇻🇪
"vietnam": 🇻🇳
"zambia": 🇿🇲
"zimbabue": 🇿🇼
"paises baixos": "🇳🇱"
"gra-bretanha": "🇬🇧"
"alemanha": 🇩🇪
"republica da coreia": 🇰🇷
"brasil": 🇧🇷

